language: php

php:
  - 5.3
  - 5.4

env:
  - NUODB_ROOT=/opt/nuodb NUODB_INCLUDE_DIR=/opt/nuodb/include NUODB_LIB_DIR=/opt/nuodb/lib64 PHP_INCLUDE_DIR=/usr/include/php5

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com
    - tgates@nuodb.com

before_install:
  - uname -a
  - phpenv versions
  - cat /etc/debian_version
  - sudo apt-get update
  - sudo apt-get install php5-dev php5-mysql
  - ls -al `php-config --extension-dir`
  - wget -q http://www.nuodb.com/latest/releases/nuodb-2.0.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - ${NUODB_ROOT}/bin/nuodbmgr --broker localhost --password bird --command "start process sm host localhost database test archive /var/tmp/nuodb initialize true"
  - ${NUODB_ROOT}/bin/nuodbmgr --broker localhost --password bird --command "start process te host localhost database test options '--dba-user dba --dba-password dba'"

install:
  - true

script:
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - make
  - echo "extension=pdo_nuodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo cp pdo_nuodb.so `php-config --extension-dir`
  - php -i
  - pear run-tests tests

after_script:
  - ${NUODB_ROOT}/bin/nuodbmgr --broker localhost --password bird --command "shutdown domain"
  - sudo dpkg -r nuodb
