language: php

php:
  - 5.3
  - 5.4

env:
  - NUODB_ROOT=/opt/nuodb NUODB_INCLUDE_DIR=/opt/nuodb/include NUODB_LIB_DIR=/opt/nuodb/lib64 PHP_INCLUDE_DIR=/usr/include/php5

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com
    - tgates@nuodb.com

before_install:
  - uname -a
  - cat /etc/debian_version
  - sudo apt-get install php5-dev
  - wget -q http://www.nuodb.com/latest/nuodb-1.0.2.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password goalie --verbose debug --archive /var/tmp/nuodb --initialize --force &
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password goalie &
  - sleep 2

install:
  - true

script:
  - cd /home/travis/build/nuodb/nuodb-php-pdo
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - make
  - echo "extension=pdo_nuodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo cp pdo_nuodb.so `php-config --extension-dir`
  - ls `php-config --extension-dir`
  - ls ~/.phpenv/versions/$(phpenv version-name)/lib/php/extensions
  - ls -al /home/travis/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/
  - ls -al /home/travis/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/no-debug-zts-20090626/
  - phpenv
  - php -i
  - pear run-tests tests/*.phpt

after_script:
  - sudo dpkg -r nuodb
