language: java

jdk:
  - openjdk7

env:
  - NUODB_ROOT=/opt/nuodb NUODB_INCLUDE_DIR=/opt/nuodb/include NUODB_LIB_DIR=/opt/nuodb/lib64 PHP_INCLUDE_DIR=/usr/local/include/php

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com

before_install:
  - sudo apt-get install php5 php-pear
  - wget -q http://www.nuodb.com/latest/nuodb-1.0-GA.linux.x86_64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password goalie --verbose debug --archive /var/tmp/nuodb --initialize --force &
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password goalie &
  - sleep 2

install:
  - true

script:
  - cd /home/travis/build/nuodb/nuodb-php-pdo
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - make
  - pear run-tests tests/*.phpt

after_script:
  - sudo dpkg -r nuodb