language: java

jdk:
  - openjdk7

env:
  - NUODB_ROOT=/opt/nuodb NUODB_INCLUDE_DIR=/opt/nuodb/include NUODB_LIB_DIR=/opt/nuodb/lib64 PHP_INCLUDE_DIR=/usr/local/include/php

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com
    - tgates@nuodb.com

before_install:
  - wget -q http://www.nuodb.com/latest/nuodb-1.0.2.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password goalie --verbose debug --archive /var/tmp/nuodb --initialize --force &
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password goalie &
  - sleep 2
  - wget -q http://www.php.net/distributions/php-5.4.3.tar.gz --output-document=/var/tmp/php-5.4.3.tar.gz
  - cd /var/tmp/ && tar xzf /var/tmp/php-5.4.3.tar.gz
  - cd /var/tmp/php-5.4.3 && ./configure --enable-shared --with-zlib --enable-cli --enable-pdo
  - cd /var/tmp/php-5.4.3 && make
  - cd /var/tmp/php-5.4.3 && sudo make install

install:
  - true

script:
  - cd /home/travis/build/nuodb/nuodb-php-pdo
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - make
  - ls -l /usr/local/lib/php/extensions
  - ls -l /usr/local/lib/php.ini
  - php -i
  - pear run-tests tests/*.phpt

after_script:
  - sudo dpkg -r nuodb