language: php

php:
  - 5.3
  - 5.4

env:
  - NUODB_ROOT=/opt/nuodb NUODB_INCLUDE_DIR=/opt/nuodb/include NUODB_LIB_DIR=/opt/nuodb/lib64 PHP_INCLUDE_DIR=/usr/local/include/php

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com
    - tgates@nuodb.com

before_install:
  - apt-cache search php
  - sudo apt-get install libxml2 libxml2-dev php5-dev
  - ls /usr/local/lib
  - ls /usr/local/include
  - which php
  - wget -q http://www.nuodb.com/latest/nuodb-1.0.2.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password goalie --verbose debug --archive /var/tmp/nuodb --initialize --force &
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password goalie &
  - sleep 2

install:
  - true

script:
  - cd /home/travis/build/nuodb/nuodb-php-pdo
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - make
  - sudo cp pdo_nuodb.so /usr/local/lib/php/extensions/no-debug-non-zts-20100525
  - php -i
  - pear run-tests tests/*.phpt

after_script:
  - sudo dpkg -r nuodb
